### ISSUE TITLE
Can't import any of these

### ISSUE THREAD

**Issue by lostinacrowd** [pebble/pebble-3d#2]
I have tried converting the STEP and STP and IGS files with a few different programs. I haven't had success with any of them. 
Has anyone else tried converting them? I'm using Unigraphics translators. An XT file would be nice since it's just a dumb solid...

**Comment by trbielec** [comment]
I would like to second this (ie. file compatibility issues).

The developer docs recommend 3D printing the smartstrap on the Form 1 or from Shapeways, yet the standard file format for both of these options is an STL file with mm units. 
@Pebble here are instructions for Solidworks to export the STEP file for 3D printing: http://forum.formlabs.com/t/for-solidworks-users/2856/4 

Thank you!

**Comment by sarfata** [comment]
Guys,

Can you try the STL files we just posted and tell me if they work better for you. Hopefully we can close this.

Thanks for your help!
thomas

**Comment by lostinacrowd** [comment]
One translator I tried said it wasn't an STL file. Another one said it had a parsing error.
I've had these kinds of issues getting solid models from vendors before. I'm never on their end knowing what they change to make it work on my end though.

**Comment by sarfata** [comment]
Can you tell us what programs you have used so we can try too?

**Comment by lostinacrowd** [comment]
I'm using the built-in translators for Unigraphics. I tried 2 different versions.

**Comment by trbielec** [comment]
@sarfata confirmed working STL for the Smartstrap connector (tested with both Makerware and PrintToPeer), watertight, and to scale. Thank you!
FYI Github also shows a visualization for the STL files: https://github.com/pebble/pebble-3d/blob/master/Pebble%20Time/Smartstrap-CAD.stl
The Pebble-Time-Exterior.stl does not appear to be a watertight mesh, so it is not directly 3D printable, but I know that's not the intention for the file, just an FYI.

**Comment by maconda99** [comment]
I've tried importing the Time files (step, iges, and stl) and the Time charging cable using both SolidWorks 2014 and Pro/E Creo 2.0 - to no success on any of the files.
